[package]
name = "tgconnector"
version = "0.0.1"
authors = ["Sreyas-Sreelal"]

[lib]
name = "tgconnector"
crate-type = ["cdylib"]

[dependencies]
samp-sdk = "0.8.4"
minihttp = {git = "https://github.com/Sreyas-Sreelal/minihttp"}
serde_json = "1.0"
serde = "*"
serde_derive = "*"
encoding = "*"