[package]
name = "tgconnector"
version = "0.1.0"
authors = ["Sreyas-Sreelal"]

[lib]
name = "tgconnector"
crate-type = ["cdylib"]

[dependencies]
samp-sdk = {git = "https://github.com/Sreyas-Sreelal/samp-sdk",branch="push_string_fix"}
minihttp = {git = "https://github.com/Sreyas-Sreelal/minihttp"}
serde_json = "1.0"
serde = "*"
serde_derive = "*"
encoding = "*"